// <auto-generated />
using AccountPersistenceDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountPersistenceDatabase.Migrations
{
    [DbContext(typeof(ApplicationAccountDbContext))]
    partial class ApplicationAccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AccountDomain.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"), 1L, 1);

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoCuenta");

                    b.HasKey("AccountId");

                    b.ToTable("Cuenta", "account");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountType = "Ahorros"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountType = "Ahorros"
                        });
                });

            modelBuilder.Entity("AccountDomain.AccountClient", b =>
                {
                    b.Property<int>("AccountClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountClientId"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("CuentaId");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumeroCuenta");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Saldo");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.HasKey("AccountClientId");

                    b.HasIndex("AccountId");

                    b.ToTable("CuentaCliente", "account");
                });

            modelBuilder.Entity("AccountDomain.AccountClient", b =>
                {
                    b.HasOne("AccountDomain.Account", "Account")
                        .WithMany("CuentasCliente")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountDomain.Account", b =>
                {
                    b.Navigation("CuentasCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
