// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovementPersistenceDatabase;

#nullable disable

namespace MovementPersistenceDatabase.Migrations
{
    [DbContext(typeof(ApplicationMovementDbContext))]
    partial class ApplicationMovementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("movement")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovementDomain.Movement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("CuentaId");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Saldo");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fechamovimiento");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoMovimiento");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Tipo");

                    b.HasKey("MovementId");

                    b.ToTable("Movimientos", "movement");

                    b.HasData(
                        new
                        {
                            MovementId = 1,
                            AccountId = 1,
                            Balance = 2000m,
                            MovementDate = new DateTime(2022, 9, 8, 15, 12, 19, 259, DateTimeKind.Local).AddTicks(4903),
                            MovementType = "Retiro de 575",
                            Value = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
