// <auto-generated />
using ClientPersistenceDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientPersistenceDatabase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("client")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClientDomain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pasword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Contrasenia");

                    b.Property<bool>("State")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Cliente", "client");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Direccion = "Otavalo sn y principal ",
                            Edad = 27,
                            Genero = "Masculino",
                            Identificacion = "1802245263",
                            Nombre = "Jose Lema",
                            Pasword = "1234",
                            State = true,
                            Telefono = "098254785 "
                        },
                        new
                        {
                            ClientId = 2,
                            Direccion = "Amazonas y  NNUU",
                            Edad = 50,
                            Genero = "Femenino",
                            Identificacion = "1804568765",
                            Nombre = "Marianela Montalvo",
                            Pasword = "5678",
                            State = true,
                            Telefono = "097548965  "
                        },
                        new
                        {
                            ClientId = 3,
                            Direccion = "13 junio y Equinoccial",
                            Edad = 37,
                            Genero = "Masculino",
                            Identificacion = "180224522001",
                            Nombre = "Juan Osorio",
                            Pasword = "4322",
                            State = true,
                            Telefono = "098874587 "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
